env:
  node: true
  es2021: true
plugins: - @typescript-eslint
extends:
  - plugin:@typescript-eslint
  - standard
  - prettier
parser: @typescript-eslint/parser
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}

# comentario no yaml