env:
  node: true
  es2021: true
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - standard
  - prettier
parser: '@typescript-eslint/parser'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  quotes:
    - error
    - backtick
  'prettier/prettier': 'error'
# comentario no yaml
